name: Publish Go to the Maven Central Repository
on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          cd finam-trade-api-go 
          go install tool

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Build proto
        run: |
          cd finam-trade-api-go
          ./gradlew build publish
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Asset GO
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./finam-trade-api-go/build/distributions/finam-trade-api-go-golang-*-golang.zip.zip
          asset_name: finam-trade-api-go-golang.zip
          asset_content_type: application/zip
      - name: Upload Asset Openapi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./finam-trade-api-go/build/distributions/finam-trade-api-go-openapiv2-*-openapiv2.zip
          asset_name: finam-trade-api-go-openapiv2.zip
          asset_content_type: application/zip
